apiVersion: apps/v1
kind: Deployment
metadata:
  name: frequent-crash-deployment
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: frequent-crash-deployment
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: frequent-crash-deployment
    spec:
      containers:
        - name: frequent-crash-container
          image: decisivedevops/k8s-restless-restarter:v1.0.0
          env:
            - name: SLEEP_TIME_RANGE
              value: "5"
